snap-board:
    ip: 127.0.0.1
    port: 7147
    firmware: /home/pi/prizm_daq/firmware/extadc_snap_spec_2020-03-22_0047.fpg
    fft-channels: 4096
    fft-shift: 0xffffffff
    accumulation-length: 393216

logging:
    level: 10

directories:
    top: /home/pi/data_100MHz
    temperatures: temperatures
    switch: switch

scio-files:
    diff: False
    compress: bzip2
    file-time: 3600

switch-control:
    sequence:
        - antenna
        - noise
        - res50
        - res100
        - short
        - open

    switches:
        calibrator:
            latching: True
            gpios:
                '1': B2
                '2': B0
                '3': A6
                '4': B1
                '5': A5
                '6': A7 
                'r': A4

    aux-gpios:
        noise-source: B4

    antenna:
        switch: calibrator
        position: 1
        ontime: 1800
        aux: None
 
    noise:
        switch: calibrator
        position: 2
        ontime: 60
        aux: None

    res50:
        switch: calibrator
        position: 3
        ontime: 60
        aux: None

    res100:
        switch: calibrator
        position: 4
        ontime: 60
        aux: None

    short:
        switch: calibrator
        position: 5
        ontime: 60
        aux: None

    open:
        switch: calibrator
        position: 6
        ontime: 60
        aux: None

temperature-sensors:
    read_interval: 10
    sensors:
        100_ambient:
            id: 28-000007a1451a
            description: 100 MHz ambient sensor (mounted on side EW)
        100EW_top_lna:
            id: 28-000007a05bc0
            description: 100 MHz side EW top LNA
        100EW_bot_lna:
            id: 28-0000079fff75
            description: 100 MHz side EW bottom LNA
        100EW_switch:
            id: 28-000007a10a52
            description: 100 MHz side EW switch
        100EW_noise:
            id: 28-000007a0bad0
            description: 100 MHz side EW noise diode
        100NS_top_lna:
            id: 28-000007a0406d
            description: 100 MHz side NS top LNA
        100NS_bot_lna:
            id: 28-000007a16f70
            description: 100 MHz side NS bottom LNA
        100NS_switch:
            id: 28-000007a12463
            description: 100 MHz side NS switch
        100NS_noise:
            id: 28-000007a14004
            description: 100 MHz side NS noise diode
